catalog/urls.py
from django.urls import path

from .views import (
    index,
    NewspaperListView,
    NewspaperDetailView,
    NewspaperCreateView,
    NewspaperUpdateView,
    NewspaperDeleteView,
    RedactorListView,
    RedactorDetailView,
    RedactorCreationView,
    RedactorDeleteView,
    TopicListView,
    TopicCreateView,
    TopicUpdateView,
    TopicDeleteView,
    toggle_assign_to_newspaper, RedactorUpdateView, register_request,
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "topic/",
        TopicListView.as_view(),
        name="topic-list",
    ),
    path(
        "topic/create/",
        TopicCreateView.as_view(),
        name="topic-create",
    ),
    path(
        "topic/<int:pk>/update/",
        TopicUpdateView.as_view(),
        name="topic-update",
    ),
    path(
        "topic/<int:pk>/delete/",
        TopicDeleteView.as_view(),
        name="topic-delete",
    ),
    path("newspapers/", NewspaperListView.as_view(), name="newspaper-list"),
    path("newspapers/<int:pk>/", NewspaperDetailView.as_view(), name="newspaper-detail"),
    path("newspapers/create/", NewspaperCreateView.as_view(), name="newspaper-create"),
    path("newspapers/<int:pk>/update/", NewspaperUpdateView.as_view(), name="newspaper-update"),
    path("newspapers/<int:pk>/delete/", NewspaperDeleteView.as_view(), name="newspaper-delete"),
    path(
        "newspapers/<int:pk>/toggle-assign/",
        toggle_assign_to_newspaper,
        name="toggle-newspaper-assign",
    ),
    path("redactors/", RedactorListView.as_view(), name="redactor-list"),
    path(
        "redactors/<int:pk>/", RedactorDetailView.as_view(), name="redactor-detail"
    ),
    path("redactor/create", RedactorCreationView.as_view(), name="redactor-create"),
    path(
        "redactor/<int:pk>/update",
        RedactorUpdateView.as_view(),
        name="redactor-update",
    ),
    path(
        "redactor/<int:pk>/delete",
        RedactorDeleteView.as_view(),
        name="redactor-delete",
    ),
    path("register/", register_request, name="register")
]

app_name = "catalog"

newspaper_agency/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse

from newspaper_agency import settings


class Topic(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Redactor(AbstractUser):
    years_of_experience = models.IntegerField(null=True, blank=True)

    class Meta:
        verbose_name = "redactor"
        verbose_name_plural = "redactors"
        ordering = ["username"]

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("catalog:redactor-detail", kwargs={"pk": self.pk})


class Newspaper(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    published_date = models.DateField(auto_now=False)
    topic = models.ForeignKey(to=Topic, on_delete=models.CASCADE)
    redactors = models.ManyToManyField(to=settings.AUTH_USER_MODEL, related_name="newspapers")

    def __str__(self):
        return f"{self.title}: {self.content}, {self.published_date}"

    class Meta:
        ordering = ["title"]

catalog/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from catalog.models import Redactor, Newspaper


class DateInput(forms.DateInput):
    input_type = 'date'


class NewspaperForm(forms.ModelForm):
    redactors = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )

    published_date = forms.DateField(widget=DateInput)

    class Meta:
        model = Newspaper
        fields = "__all__"


class RedactorCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Redactor
        fields = UserCreationForm.Meta.fields + (
            "years_of_experience",
            "first_name",
            "last_name",
        )

    def clean_years_of_experience(self):
        return validate_years_of_experience(self.cleaned_data["years_of_experience"])


class RedactorYearsOfExperienceForm(forms.ModelForm):
    class Meta:
        model = Redactor
        fields = ["years_of_experience"]

    def clean_years_of_experience(self):
        return validate_years_of_experience(self.cleaned_data["years_of_experience"])


def validate_years_of_experience(
    years_of_experience,
):
    if years_of_experience < 1:
        raise ValidationError("Years of experience should be at least 1")

    return years_of_experience


class RedactorSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search"})
    )


class NewspaperSearchForm(forms.Form):
    title = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search"})
    )


class TopicSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search"})
    )


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = Redactor
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

catalog/views.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

from catalog.forms import TopicSearchForm, NewspaperSearchForm, RedactorSearchForm, RedactorCreationForm, \
    RedactorYearsOfExperienceForm, NewspaperForm, NewUserForm
from catalog.models import Redactor, Newspaper, Topic


@login_required
def index(request):
    """View function for the home page of the site."""

    num_redactors = Redactor.objects.count()
    num_newspapers = Newspaper.objects.count()
    num_topics = Topic.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_redactors": num_redactors,
        "num_newspapers": num_newspapers,
        "num_topics": num_topics,
        "num_visits": num_visits + 1,
    }

    return render(request, "catalog/index.html", context=context)


class TopicListView(LoginRequiredMixin, generic.ListView):
    model = Topic
    context_object_name = "topic_list"
    template_name = "catalog/topic_list.html"
    paginate_by = 4
    queryset = Topic.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TopicListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = TopicSearchForm(initial={
            "name": name
        })

        return context

    def get_queryset(self):
        form = TopicSearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )

        return self.queryset


class TopicCreateView(LoginRequiredMixin, generic.CreateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("catalog:topic-list")


class TopicUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("catalog:topic-list")


class TopicDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Topic
    success_url = reverse_lazy("catalog:topic-list")


class NewspaperListView(LoginRequiredMixin, generic.ListView):
    model = Newspaper
    paginate_by = 4
    queryset = Newspaper.objects.all().select_related("topic")

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(NewspaperListView, self).get_context_data(**kwargs)

        title = self.request.GET.get("title", "")

        context["search_form"] = NewspaperSearchForm(initial={
            "title": title
        })

        return context

    def get_queryset(self):
        form = NewspaperSearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(
                title__icontains=form.cleaned_data["title"]
            )

        return self.queryset


class NewspaperDetailView(LoginRequiredMixin, generic.DetailView):
    model = Newspaper


class NewspaperCreateView(LoginRequiredMixin, generic.CreateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("catalog:newspaper-list")


class NewspaperUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("catalog:newspaper-list")


class NewspaperDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Newspaper
    success_url = reverse_lazy("catalog:newspaper-list")


class RedactorListView(LoginRequiredMixin, generic.ListView):
    model = Redactor
    paginate_by = 4
    queryset = Redactor.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(RedactorListView, self).get_context_data(**kwargs)

        username = self.request.GET.get("username", "")

        context["search_form"] = RedactorSearchForm(initial={
            "username": username
        })

        return context

    def get_queryset(self):
        form = RedactorSearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )

        return self.queryset


class RedactorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Redactor
    queryset = Redactor.objects.all().prefetch_related("newspapers__topic")


class RedactorCreationView(LoginRequiredMixin, generic.CreateView):
    model = Redactor
    form_class = RedactorCreationForm


class RedactorUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Redactor
    form_class = RedactorYearsOfExperienceForm
    success_url = reverse_lazy("catalog:redactor-list")


class RedactorDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Redactor
    success_url = reverse_lazy("catalog:redactor-list")


@login_required
def toggle_assign_to_newspaper(request, pk):
    redactor = Redactor.objects.get(id=request.user.id)
    if (
        Newspaper.objects.get(id=pk) in redactor.newspapers.all()
    ):
        redactor.newspapers.remove(pk)
    else:
        redactor.newspapers.add(pk)
    return HttpResponseRedirect(reverse_lazy("catalog:newspaper-detail", args=[pk]))


def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful." )
            return redirect("main:homepage")
        messages.error(request, "Unsuccessful registration. Invalid information.")
    form = NewUserForm()
    return render(
        request=request,
        template_name="../templates/registration/register.html",
        context={"register_form": form}
    )

templates/catalog/index.html
{% extends "base.html" %}

{% block content %}
  <header class="p-3 mb-2 text-white"
          style="background-color: lightslategrey;">
    <div class="row">
      <div class="col-sm-8 " style="">
        <h1>GNF</h1>
        <p>(Global News Finder)</p>
        <h3>Newspaper Agency # 1</h3>
      </div>
      <div class="col-sm-4 " style="">
        <div class="container">
          <p>
            <i class="fa-5x">🄶🄽🄵</i>
          </p>
        </div>
      </div>
    </div>
  </header>

  <article class="py-5 text-center" style="background-color: rgba(245, 245, 245, 0.05)">
    <h4>The GNF archive-site has the following record counts:</h4>
    <br>
    <ul style="list-style: none;">
        <li><strong>Redactors:</strong> {{ num_redactors }}</li>
        <li><strong>Newspapers:</strong> {{ num_newspapers }}</li>
        <li><strong>Topics:</strong> {{ num_topics }}</li>
    </ul>
  </article>
  <footer class="footer fixed-bottom text-light text-center"
            style="background-color: lightslategrey">
      <p>
        You have visited this page {{ num_visits }} time{{ num_visits|pluralize }}. We hope you will come back!
        <br>
        Our email: gnf@gnf.com
      </p>
    </footer>
{% endblock %}

templates/catalog/newspaper_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete newspaper?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes, delete" class="btn btn-danger"/>
    <button onclick="window.history.back();" class="btn btn-primary" type="button">Cancel</button>
  </form>
{% endblock %}

templates/catalog/newspaper_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    {{ newspaper.title }}
  </h1>
  <p>Topic: {{ newspaper.topic.name }}</p>

  <h2>
    Content:
  </h2>
    <p style="background-color: rgba(245, 245, 245, 0.4); border-radius: 4px; padding: 10px">{{ newspaper.content }}</p>
    <br>
    <h2>
      Publishers
    </h2>

    {% if newspaper in user.newspapers.all %}
      <a href="{% url 'catalog:toggle-newspaper-assign' pk=newspaper.id %}" class="btn btn-danger link-to-page">
        Delete newspaper from this publisher
      </a>
    {% else %}
      <a href="{% url 'catalog:toggle-newspaper-assign' pk=newspaper.id %}" class="btn btn-secondary link-to-page">
        Assign newspaper to me
      </a>
    {% endif %}

  </h1>
  <hr>
  <ul style="background-color: rgba(245, 245, 245, 0.4); border-radius: 4px; padding-left: 20px">
    {% for redactor in newspaper.redactors.all %}
      <li>{{ redactor.username }}
        ({{ redactor.first_name }} {{ redactor.last_name }},
        {{ redactor.years_of_experience }} year{{ redactor.years_of_experience|pluralize }})</li>
    {% endfor %}
  </ul>
  <br>
  <a href="{% url 'catalog:newspaper-delete' pk=newspaper.id %}" class="btn btn-danger link-to-page">
      Delete
  </a>

  <a href="{% url 'catalog:newspaper-update' pk=newspaper.id %}" class="btn btn-secondary link-to-page">
      Update
  </a>
{% endblock %}

templates/catalog/newspaper_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div style="background-color: rgba(245, 245, 245, 0.1)">
    <h1>{{ object|yesno:"Update,Create" }} newspaper</h1>
    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}

      <input type="submit" value="Submit" class="btn btn-primary">
      <button onclick="window.history.back();" class="btn btn-danger" type="button">Cancel</button>
    </form>
  </div>
{% endblock %}

templates/catalog/newspaper_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Newspaper list
    <a href="{% url 'catalog:newspaper-create' %}" class="btn btn-primary link-to-page">
      Add newspaper
    </a>
  </h1>

  <br>
  <form action="" method="get" class="form-inline">
    {{ search_form|crispy }}
    <input type="submit" class="btn btn-secondary" value="🔍">
  </form>

  <br>

  {% if newspaper_list %}
    <table class="table table-hover" style="background-color: rgba(245, 245, 245, 0.4)">
      <tr>
        <th>ID</th>
        <th>Title</th>
        <th>Published date</th>
        <th>Topic</th>
      </tr>
    {% for newspaper in newspaper_list %}
      <tr>
        <td><a href="{% url "catalog:newspaper-detail" pk=newspaper.id %} ">{{ newspaper.id }}</a></td>
        <td>{{ newspaper.title }}</td>
        <td>{{ newspaper.published_date }}</td>
        <td>{{ newspaper.topic.name }}</td>
      </tr>
    {% endfor %}
    </table>
  {% else %}
    <p>There are no newspaper in catalog</p>
  {% endif %}
{% endblock %}

templates/catalog/redactor_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete redactor?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <button onclick="window.history.back();" class="btn btn-primary" type="button">Cancel</button>
  </form>
{% endblock %}

templates/catalog/redactor_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Username: {{ redactor.username }}
  </h1>
  <br>

  <p><strong>First name:</strong> {{ redactor.first_name }}</p>
  <p><strong>Last name:</strong> {{ redactor.last_name }}</p>
  <p><strong>Years of experience:</strong> {{ redactor.years_of_experience }}</p>
  <p><strong>Is staff:</strong> {{ redactor.is_staff }}</p>

  <div class="ml-3">
    <h4>Newspapers</h4>


    {% if redactor.newspapers.all %}
    <table class="table table-hover" style="background-color: rgba(245, 245, 245, 0.4)">
      <tr>
        <th>ID</th>
        <th>Title</th>
        <th>Published date</th>
        <th>Topic</th>
      </tr>
    {% for newspaper in redactor.newspapers.all %}
      <tr>
        <td><a href="{% url "catalog:newspaper-detail" pk=newspaper.id %} ">{{ newspaper.id }}</a></td>
        <td>{{ newspaper.title }}</td>
        <td>{{ newspaper.published_date }}</td>
        <td>{{ newspaper.topic.name }}</td>
      </tr>
    {% endfor %}
    </table>
    {% else %}
      <p>No newspapers!</p>
    {% endif %}
  </div>
  <br>
  <a href="{% url 'catalog:redactor-delete' pk=redactor.id %}" class="btn btn-danger link-to-page">
      Delete
  </a>

  <a href="{% url 'catalog:redactor-update' pk=redactor.id %}" class="btn btn-secondary link-to-page">
      Update
  </a>
{% endblock %}

templates/catalog/redactor_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div style="background-color: rgba(245, 245, 245, 0.1)">
    <h1>{{ object|yesno:"Update,Create" }} redactor</h1>
    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}

      <input type="submit" value="Submit" class="btn btn-primary">
      <button onclick="window.history.back();" class="btn btn-danger" type="button">Cancel</button>
    </form>
  </div>
{% endblock %}

templates/catalog/redactor_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
    <h1>
      Redactor List
      <a href="{% url 'catalog:redactor-create' %}" class="btn btn-primary link-to-page">
        Add redactor
      </a>
    </h1>

  <br>
  <form action="" method="get" class="form-inline">
    {{ search_form|crispy }}
    <input type="submit" class="btn btn-secondary" value="🔍">
  </form>

  <br>

    {% if redactor_list %}
    <table class="table table-hover" style="background-color: rgba(245, 245, 245, 0.4)">
      <tr>
        <th>ID</th>
        <th>Username</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Years of experience</th>
      </tr>
    {% for redactor in redactor_list %}
      <tr>
        <td>{{ redactor.id }}</td>
        <td><a href="{{ redactor.get_absolute_url }}">{{ redactor.username }} {% if user == redactor %} (Me){% endif %}</a></td>
        <td>{{ redactor.first_name }}</td>
        <td>{{ redactor.last_name }}</td>
        <td>{{ redactor.years_of_experience }}</td>
      </tr>
    {% endfor %}

    </table>
    {% else %}
      <p>There are no redactors in the newspaper agency.</p>
    {% endif %}
{% endblock %}

templates/catalog/topic_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete topic?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <button onclick="window.history.back();" class="btn btn-primary" type="button">Cancel</button>
  </form>
{% endblock %}

templates/catalog/topic_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div style="background-color: rgba(245, 245, 245, 0.1)">
    <h1>{{ object|yesno:"Update,Create" }} topic</h1>
    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}

      <input type="submit" value="Submit" class="btn btn-primary">
      <button onclick="window.history.back();" class="btn btn-danger" type="button">Cancel</button>
    </form>
  </div>
{% endblock %}

templates/catalog/topic_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Topic List
    <a href="{% url 'catalog:topic-create' %}" class="btn btn-primary link-to-page">
      Add topic
    </a>
  </h1>

  <br>
  <form action="" method="get" class="form-inline">
    {{ search_form|crispy }}
    <input type="submit" class="btn btn-secondary" value="🔍">
  </form>

  <br>

  {% if topic_list %}
    <table class="table table-hover" style="background-color: rgba(245, 245, 245, 0.4)">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for topic in topic_list %}
        <tr>
          <td>
              {{ topic.id }}
          </td>
          <td>
              {{ topic.name }}
          </td>
          <td>
            <a href="{% url 'catalog:topic-update' pk=topic.id %}">
              <span class="btn btn-access btn-sm" style="padding-left: 10px"> 📝 </span>
            </a>
          </td>
          <td>
            <a href="{% url 'catalog:topic-delete' pk=topic.id %}">
              <span class="btn btn-access btn-sm" style="padding-left: 10px"> ❌ </span>️
            </a>
          </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>There are no topic in the newspaper agency.</p>
  {% endif %}
{% endblock %}